export const METADATA_ERRORS = {
  IMAGE_CREATION: 'IMAGE_CREATION.METADATA_ERRORS',
  IMAGE_NOT_FOUND: 'IMAGE_NOT_FOUND.METADATA_ERRORS',
};

export const AWS_ERRORS = {
  IMAGE_UPLOAD: 'IMAGE_UPLOAD.AWS_ERRORS',
};
